# Generated by Django 5.2.6 on 2025-10-19 01:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segundo_nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Nombre')),
                ('segundo_apellido', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Apellido')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte')], max_length=3, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Solo se permiten números')], verbose_name='Número de Documento')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefono_principal', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'El teléfono debe tener 10 dígitos')], verbose_name='Teléfono Principal')),
                ('telefono_secundario', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'El teléfono debe tener 10 dígitos')], verbose_name='Teléfono Secundario')),
                ('direccion', models.CharField(max_length=60, verbose_name='Dirección de Residencia')),
                ('ciudad', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('numero_licencia', models.CharField(max_length=20, verbose_name='Número de Licencia')),
                ('licencia_expedicion', models.DateField(verbose_name='Fecha de Expedición de Licencia')),
                ('licencia_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento de Licencia')),
                ('tipo_cuenta', models.CharField(choices=[('Ahorros', 'Ahorros'), ('Corriente', 'Corriente')], max_length=10, verbose_name='Tipo de Cuenta')),
                ('banco', models.CharField(max_length=50, verbose_name='Banco')),
                ('numero_cuenta', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Solo se permiten números')], verbose_name='Número de Cuenta')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de Verificación'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Suspendido', 'Suspendido')], default='Pendiente', max_length=15, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conductor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'db_table': 'conductor',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('documento_frontal', 'Documento de Identidad Frontal'), ('documento_reverso', 'Documento de Identidad Reverso'), ('tarjeta_propiedad', 'Tarjeta de Propiedad'), ('certificado_reconocimiento', 'Certificado de Reconocimiento'), ('foto_licencia', 'Foto de Licencia'), ('documento_soat', 'Documento SOAT'), ('antecedentes_judiciales', 'Antecedentes Judiciales'), ('foto_vehiculo_frontal', 'Foto Vehículo Frontal'), ('foto_vehiculo_lateral', 'Foto Vehículo Lateral'), ('foto_vehiculo_interior', 'Foto Vehículo Interior'), ('certificado_tecnomecanica', 'Certificado de Tecnomecánica')], max_length=30, verbose_name='Tipo de Documento')),
                ('archivo', models.FileField(upload_to='documentos_conductores/%Y/%m/%d/', verbose_name='Archivo')),
                ('nombre_original', models.CharField(max_length=255, verbose_name='Nombre Original del Archivo')),
                ('tamaño_archivo', models.PositiveIntegerField(verbose_name='Tamaño del Archivo (bytes)')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='src.conductor', verbose_name='Conductor')),
            ],
            options={
                'verbose_name': 'Documento de Conductor',
                'verbose_name_plural': 'Documentos de Conductores',
                'db_table': 'documento_conductor',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=6, unique=True, verbose_name='Placa del Vehículo')),
                ('marca', models.CharField(max_length=30, verbose_name='Marca del Vehículo')),
                ('modelo', models.CharField(max_length=30, verbose_name='Modelo del Vehículo')),
                ('anio', models.PositiveIntegerField(verbose_name='Año del Vehículo')),
                ('color', models.CharField(max_length=20, verbose_name='Color del Vehículo')),
                ('tipo_vehiculo', models.CharField(max_length=20, verbose_name='Tipo de Vehículo')),
                ('num_pasajeros', models.PositiveIntegerField(verbose_name='Número de Pasajeros')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('conductor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='src.conductor', verbose_name='Conductor')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculo',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddIndex(
            model_name='conductor',
            index=models.Index(fields=['numero_documento'], name='conductor_numero__0b630f_idx'),
        ),
        migrations.AddIndex(
            model_name='conductor',
            index=models.Index(fields=['estado'], name='conductor_estado_1a7f17_idx'),
        ),
        migrations.AddIndex(
            model_name='documentoconductor',
            index=models.Index(fields=['conductor'], name='documento_c_conduct_ee009e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentoconductor',
            index=models.Index(fields=['tipo_documento'], name='documento_c_tipo_do_0d9d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['placa'], name='vehiculo_placa_739f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['conductor'], name='vehiculo_conduct_e0179b_idx'),
        ),
    ]
