# Generated by Django 5.2.6 on 2025-10-30 23:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_conductor_documentoconductor_vehiculo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstadoConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('Pendiente', 'Pendiente de Verificación'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Suspendido', 'Suspendido')], max_length=15, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(choices=[('Pendiente', 'Pendiente de Verificación'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Suspendido', 'Suspendido')], max_length=15, verbose_name='Estado Nuevo')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Cambio')),
                ('motivo', models.CharField(choices=[('Registro', 'Registro inicial'), ('Verificacion', 'Verificación de documentos'), ('Pago', 'Pago pendiente'), ('Queja', 'Queja de cliente'), ('Mantenimiento', 'Mantenimiento del vehículo'), ('Licencia', 'Licencia vencida'), ('Manual', 'Cambio manual por administrador'), ('Reincidente', 'Comportamiento reincidente'), ('Reactivacion', 'Reactivación por cumplimiento'), ('Otro', 'Otro motivo')], default='Manual', max_length=20, verbose_name='Motivo del Cambio')),
                ('descripcion_motivo', models.TextField(blank=True, null=True, verbose_name='Descripción del Motivo')),
                ('notas_internas', models.TextField(blank=True, null=True, verbose_name='Notas Internas')),
                ('ip_modificador', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP del modificador')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='src.conductor', verbose_name='Conductor')),
                ('usuario_modificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_conductores', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el cambio')),
            ],
            options={
                'verbose_name': 'Cambio de Estado del Conductor',
                'verbose_name_plural': 'Historial de Estados de Conductores',
                'db_table': 'historial_estado_conductor',
                'ordering': ['-fecha_cambio'],
                'indexes': [models.Index(fields=['conductor', '-fecha_cambio'], name='historial_e_conduct_fe2db5_idx'), models.Index(fields=['fecha_cambio'], name='historial_e_fecha_c_ff70d8_idx'), models.Index(fields=['motivo'], name='historial_e_motivo_3f4ccd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(verbose_name='Fecha de Solicitud')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('estado', models.CharField(choices=[('Solicitado', 'Solicitado'), ('Aceptado', 'Aceptado'), ('En Progreso', 'En Progreso'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado'), ('Rechazado', 'Rechazado')], default='Solicitado', max_length=15, verbose_name='Estado del Viaje')),
                ('origen', models.CharField(max_length=100, verbose_name='Dirección de Origen')),
                ('destino', models.CharField(max_length=100, verbose_name='Dirección de Destino')),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Distancia (km)')),
                ('tiempo_estimado', models.DurationField(blank=True, null=True, verbose_name='Tiempo Estimado')),
                ('tiempo_real', models.DurationField(blank=True, null=True, verbose_name='Tiempo Real')),
                ('calificacion_cliente', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación del Cliente')),
                ('comentario_cliente', models.TextField(blank=True, null=True, verbose_name='Comentario del Cliente')),
                ('calificacion_conductor', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación del Conductor')),
                ('comentario_conductor', models.TextField(blank=True, null=True, verbose_name='Comentario del Conductor')),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Base')),
                ('valor_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Adicional')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta de Crédito/Débito'), ('Transferencia', 'Transferencia Bancaria'), ('App', 'Pago en App')], default='Efectivo', max_length=15, verbose_name='Método de Pago')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='src.cliente', verbose_name='Cliente')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='src.conductor', verbose_name='Conductor')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'db_table': 'viaje',
                'ordering': ['-fecha_solicitud'],
                'indexes': [models.Index(fields=['conductor', '-fecha_solicitud'], name='viaje_conduct_4338b0_idx'), models.Index(fields=['cliente', '-fecha_solicitud'], name='viaje_cliente_703f47_idx'), models.Index(fields=['estado'], name='viaje_estado_03faa4_idx'), models.Index(fields=['fecha_solicitud'], name='viaje_fecha_s_20ff68_idx')],
            },
        ),
    ]
