# Generated by Django 5.2.6 on 2025-10-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_historialestadoconductor_viaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='estado',
            field=models.CharField(choices=[('Pendiente de Verificación', 'Pendiente de Verificación'), ('En Corrección', 'En Corrección'), ('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Suspendido', 'Suspendido'), ('Bloqueado', 'Bloqueado'), ('Rechazado', 'Rechazado'), ('Dado de Baja', 'Dado de Baja')], default='Pendiente', max_length=40, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historialestadoconductor',
            name='estado_anterior',
            field=models.CharField(choices=[('Pendiente de Verificación', 'Pendiente de Verificación'), ('En Corrección', 'En Corrección'), ('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Suspendido', 'Suspendido'), ('Bloqueado', 'Bloqueado'), ('Rechazado', 'Rechazado'), ('Dado de Baja', 'Dado de Baja')], max_length=40, verbose_name='Estado Anterior'),
        ),
        migrations.AlterField(
            model_name='historialestadoconductor',
            name='estado_nuevo',
            field=models.CharField(choices=[('Pendiente de Verificación', 'Pendiente de Verificación'), ('En Corrección', 'En Corrección'), ('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Suspendido', 'Suspendido'), ('Bloqueado', 'Bloqueado'), ('Rechazado', 'Rechazado'), ('Dado de Baja', 'Dado de Baja')], max_length=40, verbose_name='Estado Nuevo'),
        ),
        migrations.AlterField(
            model_name='historialestadoconductor',
            name='motivo',
            field=models.CharField(choices=[('Registro', 'Registro inicial'), ('Verificacion', 'Verificación de documentos'), ('Correccion', 'Solicitud de corrección'), ('Aprobacion', 'Aprobación de documentos'), ('Activacion', 'Activación manual'), ('Inactivacion', 'Inactivación voluntaria'), ('Suspension', 'Suspensión por incumplimiento'), ('Bloqueo', 'Bloqueo por infracciones graves'), ('Rechazo', 'Rechazo por no cumplir requisitos'), ('Baja', 'Dado de baja'), ('Reactivacion', 'Reactivación por cumplimiento'), ('Licencia', 'Licencia vencida'), ('Queja', 'Queja de cliente'), ('Pago', 'Pago pendiente'), ('Otro', 'Otro motivo')], default='Manual', max_length=20, verbose_name='Motivo del Cambio'),
        ),
    ]
