# Generated by Django 5.2.6 on 2025-11-02 15:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_alter_conductor_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_novedad', models.CharField(choices=[('Accidente', 'Accidente'), ('Retraso', 'Retraso'), ('Cancelación', 'Cancelación'), ('Queja Cliente', 'Queja del Cliente'), ('Queja Conductor', 'Queja del Conductor'), ('Vehículo Averiado', 'Vehículo Averiado'), ('Cambio de Ruta', 'Cambio de Ruta'), ('Incidente', 'Incidente'), ('Otro', 'Otro')], max_length=30, verbose_name='Tipo de Novedad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Revisión', 'En Revisión'), ('Resuelta', 'Resuelta'), ('Cerrada', 'Cerrada'), ('Escalada', 'Escalada')], default='Pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('resolucion', models.TextField(blank=True, null=True, verbose_name='Resolución')),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Crítica', 'Crítica')], default='Media', max_length=10, verbose_name='Prioridad')),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'db_table': 'novedad',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cargo/Posición'),
        ),
        migrations.AddField(
            model_name='compania',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='compania',
            name='email_corporativo',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email Corporativo'),
        ),
        migrations.AddField(
            model_name='compania',
            name='estado_cuenta',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Suspendida', 'Suspendida'), ('Morosa', 'Morosa'), ('Cancelada', 'Cancelada')], default='Activa', max_length=20, verbose_name='Estado de Cuenta'),
        ),
        migrations.AddField(
            model_name='compania',
            name='fecha_membresia',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Membresía'),
        ),
        migrations.AddField(
            model_name='compania',
            name='persona_contacto',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Persona de Contacto'),
        ),
        migrations.AddField(
            model_name='compania',
            name='razon_social',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='compania',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'El teléfono debe tener 10 dígitos')], verbose_name='Teléfono'),
        ),
        migrations.AddIndex(
            model_name='compania',
            index=models.Index(fields=['nit'], name='compania_nit_b619e5_idx'),
        ),
        migrations.AddIndex(
            model_name='compania',
            index=models.Index(fields=['estado_cuenta'], name='compania_estado__c4fa3a_idx'),
        ),
        migrations.AddField(
            model_name='novedad',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='src.cliente', verbose_name='Cliente Involucrado'),
        ),
        migrations.AddField(
            model_name='novedad',
            name='compania',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='src.compania', verbose_name='Compañía Asociada'),
        ),
        migrations.AddField(
            model_name='novedad',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='src.conductor', verbose_name='Conductor Involucrado'),
        ),
        migrations.AddField(
            model_name='novedad',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='novedad',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_resueltas', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto Por'),
        ),
        migrations.AddField(
            model_name='novedad',
            name='viaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='src.viaje', verbose_name='Viaje Asociado'),
        ),
        migrations.AddIndex(
            model_name='novedad',
            index=models.Index(fields=['tipo_novedad'], name='novedad_tipo_no_e12ea6_idx'),
        ),
        migrations.AddIndex(
            model_name='novedad',
            index=models.Index(fields=['estado'], name='novedad_estado_af8cac_idx'),
        ),
        migrations.AddIndex(
            model_name='novedad',
            index=models.Index(fields=['fecha_creacion'], name='novedad_fecha_c_f35361_idx'),
        ),
        migrations.AddIndex(
            model_name='novedad',
            index=models.Index(fields=['compania', '-fecha_creacion'], name='novedad_compani_b70e01_idx'),
        ),
    ]
