# Generated by Django 5.2.6 on 2025-11-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_alter_conductor_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Corrección', 'En Corrección'), ('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Suspendido', 'Suspendido'), ('Bloqueado', 'Bloqueado'), ('Rechazado', 'Rechazado'), ('Dado de Baja', 'Dado de Baja')], default='Pendiente', max_length=40, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historialestadoconductor',
            name='estado_anterior',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Corrección', 'En Corrección'), ('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Suspendido', 'Suspendido'), ('Bloqueado', 'Bloqueado'), ('Rechazado', 'Rechazado'), ('Dado de Baja', 'Dado de Baja')], max_length=40, verbose_name='Estado Anterior'),
        ),
        migrations.AlterField(
            model_name='historialestadoconductor',
            name='estado_nuevo',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Corrección', 'En Corrección'), ('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Suspendido', 'Suspendido'), ('Bloqueado', 'Bloqueado'), ('Rechazado', 'Rechazado'), ('Dado de Baja', 'Dado de Baja')], max_length=40, verbose_name='Estado Nuevo'),
        ),
    ]
